# Generated by Django 5.1.2 on 2025-12-03 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('subscription_plan', models.CharField(db_index=True, default='basic', max_length=50)),
                ('subscription_status', models.CharField(db_index=True, default='active', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scenarios', models.JSONField()),
                ('comparison_results', models.JSONField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='simulation.restaurant')),
            ],
            options={
                'db_table': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_configs', to='simulation.restaurant')),
            ],
            options={
                'db_table': 'simulation_configs',
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('config', models.JSONField()),
                ('results', models.JSONField()),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='completed', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('config_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='simulation.simulationconfig')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='simulation.restaurant')),
            ],
            options={
                'db_table': 'simulation_results',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('priority', models.CharField(default='medium', max_length=50)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('recommended_value', models.JSONField(blank=True, null=True)),
                ('expected_improvements', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('cost_analysis', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='simulation.restaurant')),
                ('simulation', models.ForeignKey(db_column='simulation_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='simulation.simulationresult', to_field='simulation_id')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='idx_owner_id'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['subscription_plan', 'subscription_status'], name='idx_subscription'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['restaurant'], name='idx_experiment_restaurant'),
        ),
        migrations.AddIndex(
            model_name='simulationconfig',
            index=models.Index(fields=['restaurant'], name='idx_simcfg_restaurant'),
        ),
        migrations.AddIndex(
            model_name='simulationconfig',
            index=models.Index(fields=['created_at'], name='idx_simcfg_created_at'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['restaurant'], name='idx_simres_restaurant'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['created_at'], name='idx_simres_created_at'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['status'], name='idx_simres_status'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['simulation'], name='idx_rec_simulation'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['restaurant'], name='idx_rec_restaurant'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status'], name='idx_rec_status'),
        ),
    ]
