
services:
  web:
    build: .
    container_name: queueopt-web
    command: >
      sh -c "python manage.py makemigrations 2>&1 || echo 'No new migrations needed' &&
              python manage.py migrate && 
              python manage.py collectstatic --noinput &&
              gunicorn config.wsgi:application --bind 0.0.0.0:4400 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "4400:4400"
    restart: always

  db:
    image: postgres:16-alpine
    container_name: queueopt-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  # redis:
  #   image: redis:7-alpine
  #   container_name: queueopt-redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  redis:
    image: redis:7-alpine
    container_name: queueopt-redis
    ports:
      - "6380:6379"
    restart: always

volumes:
  db_data:
  static_volume:
