# Generated by Django 5.1.2 on 2025-12-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_recommendation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='simulation.restaurant'),
        ),
    ]
